version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3-bullseye
        NODE_VERSION: "none"
    environment:
      # Media storage
      STORAGE_ACCESS_KEY: minio
      STORAGE_SECRET_KEY: miniosecret
      STORAGE_ENDPOINT_URL: http://minio:9000
      STORAGE_REGION: us-east-1
      STORAGE_BUCKET: myapp

    volumes:
      - ..:/workspace:cached
    command: sleep infinity


  minio:
    image: docker.io/bitnami/minio:2022
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniosecret
      MINIO_DEFAULT_BUCKETS: myapp
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"


volumes:
  minio-data:
    driver: local
